import './globals.css';
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Sher's Next App",
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <meta httpEquiv='Content-Security-Policy' content="img-src 'self'; frame-src 'self';"></meta>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
