name: make our CI/CD powerful
run-name: Hey, ${{github.actor}}, Let's do it.

env:
  NODE_VERSION: 18.18.0
  PNPM_VERSION: 8.6.2

# trunk-based way
on:
  push:
    branches:
      - main
      - release/*
      - github-action
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{env.PNPM_VERSION}}
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{env.PNPM_STORE_PATH}}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup cypress cache
        uses: actions/cache@v3
        with:
          path: '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-Cypress-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  test:
    runs-on: ubuntu-latest

    steps:
      # fetch main but checkout current next, for nx affected defaultBase
      - uses: actions/checkout@v4
        with:
          ref: main

      - run: echo "REF=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      - run: git fetch origin ${{ env.REF }}

      - name: checkout current
        run: git checkout ${{ env.REF }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{env.PNPM_VERSION}}
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: restore cache from pnpm store
        uses: actions/cache@v3
        with:
          fail-on-cache-miss: true
          path: ${{env.PNPM_STORE_PATH}}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: restore cache from cypress
        uses: actions/cache@v3
        with:
          fail-on-cache-miss: true
          path: '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-Cypress-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install cypress
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          install: false
          component: true
          start: npm start

      - name: Unit test in affected package
        run: npm run test:affected

    needs: setup
