name: make our CI/CD powerful
run-name: Hey, ${{github.actor}}, Let's do it.

env:
  NODE_VERSION: 18.18.0
  PNPM_VERSION: 8.6.2

# trunk-based way
on:
  push:
    branches:
      # - main
      # - release/*
      - github-action
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # fetch main but checkout current next, for nx affected defaultBase
      - uses: actions/checkout@v4
        with:
          ref: main

      - run: echo "REF=${{ github.event.pull_request && github.base_ref || github.ref_name }}" >> $GITHUB_ENV

      - run: git fetch ${{ env.REF }}
      - run: echo ${{ env.REF }}
      - run: echo $REF

      - name: checkout current
        run: git checkout ${{ env.REF }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
